apiVersion: apps/v1
kind: Deployment
metadata:
  name: roxie-r1
  labels:
    app: roxie-r1
spec:  # specification of the pod’s contents
  replicas: 1
  selector:
    matchLabels:
      app: roxie-r1
      cluster: r1
  template:
    metadata:
      labels:
        app: roxie-r1
        cluster: r1
    spec:
      containers:
        - name:  roxie-r1
          image: "hpccsystems/hpcc-elastic"
