apiVersion: v1
kind: ReplicationController
metadata:
  name: esp-controller
spec:
  replicas: 2
  selector:
    app: esp
  template:
    metadata:
      labels:
        app: esp 
    spec:
      containers:
      - name: esp
        image: "hpccsystems/platform-ce:6.0.2-1trusty"
        ports:
          - containerPort: 8010
