apiVersion: v1
kind: ReplicationController
metadata:
  name: roxie-controller
spec:
  replicas: 2
  selector:
    app: roxie
  template:
    metadata:
      labels:
        app: roxie
    spec:
      containers:
      - name: roxie
        image: "hpccsystems/platform-ce:6.0.2-1trusty"
