apiVersion: v1
kind: ReplicationController
metadata:
  name: master-controller
spec:
  replicas: 1
  selector:
    app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: master
        command: ["/bin/bash","-c","cd /tmp && /tmp/run_master.sh"]
        image: "hpccsystems/platform-ce:5.4.8-1trusty"
        ports:
        - containerPort: 8010

