apiVersion: v1
kind: Pod
metadata:
  name: dali
spec:  # specification of the pod’s contents
  restartPolicy: Never
  containers:
  - name:  dali
    image: "hpccsystems/platform"
    volumeMounts:
    - mountPath: "/var/lib/HPCCSystems"
      name: dali-data
  volumes:
  - name: dali-data
    persistentVolumeClaim:
      claimName: dali-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dali-data 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 40Gi
