apiVersion: v1
kind: Pod
metadata:
  name: dali
spec:  # specification of the pod’s contents
  restartPolicy: Never
  containers:
  - name:  dali
    image: "hpccsystems/platform"
    volumeMounts:
    - mountPath: "/var/lib/HPCCSystems/hpcc-data"
      name: dali-data
  volumes:
  - name: dali-data
    persistentVolumeClaim:
      claimName: efs
