#!/bin/bash

WORK_DIR=$(dirname $0)
. ${WORK_DIR}/../../bin/common


${KUBECTL}.sh delete -f admin.yaml
#${KUBECTL}.sh delete -f dali-sf.yaml
${KUBECTL}.sh delete -f support-sf.yaml
${KUBECTL}.sh delete -f esp-e1-sf.yaml


#${KUBECTL}.sh delete -f support.yaml
#${KUBECTL}.sh delete svc esp-e1
##${KUBECTL}.sh delete -f roxie-r1.yaml
#${KUBECTL}.sh delete -f thormaster-t1.yaml
#${KUBECTL}.sh delete -f thor-t1.yaml
