apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: eclwatch
  namespace: default
spec:
  rules:
  #- services: ["*"]
  - services: ["esp-e1"]
    #constraints:
    #- key: "destination.port"
    #  values: ["8010"]
