apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-default
  labels:
    config-type: default
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 10.103.25.235
    #path: /hpcc-config/default
    path: /tmp
