#!/bin/bash

kubectl.exe create -f nfs-server-rc.yaml
kubectl.exe create -f nfs-server-service.yaml
sleep 5
nfs_service_ip=$(kubectl.exe get service | grep nfs-server| sed -n 's/  */ /gp' | cut -d' ' -f3)
sed  "s/<NFS_SERVICE_IP>/${nfs_service_ip}/g"  config-default-pv-template.yaml > config-pv.yaml
echo ""
echo "$nfs_service_ip"

kubectl.exe create -f config-pv.yaml
kubectl.exe create -f config-pvc.yaml

echo ""
echo "kubectl.exe get service"
kubectl.exe get service
echo ""
echo "kubectl.exe get pv"
kubectl.exe get pv
echo ""
echo "kubectl.exe get pvc"
kubectl.exe get pvc

kubectl.exe create -f hpcc-rc.yaml
echo ""
echo "kubectl.exe get pod"
kubectl.exe get pod
echo ""




