apiVersion: apps/v1
kind: Deployment
metadata:
  name: thor-thor1
spec:  # specification of the pod’s contents
  replicas: 2
  selector:
    matchLabels:
      app: thor-thor1
  template:
    metadata:
      labels:
        app: thor-thor1
    spec:
      containers:
      - name:  thor-thor1
        image: "hpccsystems/platform"
        volumeMounts:
        - mountPath: "/var/lib/HPCCSystems/hpcc-data"
          name: thor1-efs-pvc
      volumes:
      - name: thor1-efs-pvc
        persistentVolumeClaim:
          claimName: efs
