apiVersion: v1
kind: Service
metadata:
  name: esp-e1
  namespace: default
  labels:
    app: esp-e1
spec:
  ports:
  - port: 8010
    name: esp-e1
  clusterIP: None
  selector:
    name: esp-e1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: esp-e1
spec:  # specification of the pod’s contents
  serviceName: "esp-e1"
  replicas: 2
  selector:
    matchLabels:
      app: esp-e1
  template:
    metadata:
      labels:
        app: esp-e1
    spec:
      containers:
        - name: esp-e1 
          image: "hpccsystems/hpcc:7.2.20-1"
          ports:
            - name: eclwatch
              containerPort: 8010 
            - name: wsecl
              containerPort: 8010 
            - name: roxie
              containerPort: 9876 
