#!/bin/bash
kubectl.sh delete -f admin.yaml
kubectl.sh delete -f support.yaml
#kubectl.sh delete -f esp-e1.yaml
kubectl.sh delete -f roxie-r1.yaml
#kubectl.sh delete -f thormaster-t1.yaml
#kubectl.sh delete -f thor-t1.yaml
